services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registry
    ports:
      - "5432:5432"
    volumes:
      - registry_data:/var/lib/postgresql/data

volumes:
  registry_data: